#
# Imports

In [2]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import requests

#
# Reading CSV files with all the links

In [7]:
links = pd.read_csv('HomeLinks.csv')
links

           links
0    /119964742/
1    /119635173/
2    /119584666/
3    /119380606/
4    /119204643/
..           ...
807  /118738557/
808  /118697846/
809  /116195702/
810  /116116452/
811  /114930351/

[812 rows x 1 columns]

#
# Scraping

###
### Converting the links DataFrame into a list to iterate through

In [8]:
links = links.values.tolist()

In [9]:
len(links)

812

In [10]:
links

[['/119964742/'],
 ['/119635173/'],
 ['/119584666/'],
 ['/119380606/'],
 ['/119204643/'],
 ['/119159606/'],
 ['/118901059/'],
 ['/118911877/'],
 ['/117988842/'],
 ['/116216072/'],
 ['/116057736/'],
 ['/115994216/'],
 ['/117540071/'],
 ['/117995512/'],
 ['/117537643/'],
 ['/112907687/'],
 ['/112770910/'],
 ['/111865974/'],
 ['/117534146/'],
 ['/119923779/'],
 ['/119880732/'],
 ['/119585169/'],
 ['/119365415/'],
 ['/119262236/'],
 ['/119052099/'],
 ['/118928357/'],
 ['/118715611/'],
 ['/118781864/'],
 ['/118628363/'],
 ['/118553948/'],
 ['/118344975/'],
 ['/118314333/'],
 ['/117651842/'],
 ['/117576026/'],
 ['/115049657/'],
 ['/119321648/'],
 ['/119408482/'],
 ['/119009129/'],
 ['/118503258/'],
 ['/119618274/'],
 ['/119437292/'],
 ['/119416998/'],
 ['/119254320/'],
 ['/119159612/'],
 ['/119005911/'],
 ['/118663455/'],
 ['/114157724/'],
 ['/117536452/'],
 ['/119880733/'],
 ['/119789616/'],
 ['/119274665/'],
 ['/119118255/'],
 ['/119071879/'],
 ['/118785300/'],
 ['/118258684/'],
 ['/118162313/'],
 ['/118010741/'],
 ['/119944790/'],
 ['/119828768/'],
 ['/119812178/'],
 ['/119769587/'],
 ['/119769646/'],
 ['/119750352/'],
 ['/119706718/'],
 ['/119648198/'],
 ['/119654535/'],
 ['/119512365/'],
 ['/119556982/'],
 ['/119561664/'],
 ['/119267305/'],
 ['/119282271/'],
 ['/119546736/'],
 ['/119472006/'],
 ['/119492388/'],
 ['/119413938/'],
 ['/119232494/'],
 ['/119208793/'],
 ['/119208801/'],
 ['/119210283/'],
 ['/118984409/'],
 ['/119101464/'],
 ['/119052095/'],
 ['/119009136/'],
 ['/118898849/'],
 ['/118948354/'],
 ['/118905937/'],
 ['/118833913/'],
 ['/118797743/'],
 ['/118767755/'],
 ['/118736457/'],
 ['/118676159/'],
 ['/118653894/'],
 ['/118580153/'],
 ['/118548057/'],
 ['/118497294/'],
 ['/118414669/'],
 ['/118251731/'],
 ['/118389365/'],
 ['/118108569/'],
 ['/118208542/'],
 ['/118306611/'],
 ['/117898358/'],
 ['/117881413/'],
 ['/117817524/'],
 ['/117745687/'],
 ['/117578470/'],
 ['/116216667/'],
 ['/116215634/'],
 ['/116116957/'],
 ['/115995036/'],
 ['/118125894/'],
 ['/115676632/'],
 ['/115115838/'],
 ['/117540155/'],
 ['/115049412/'],
 ['/117538353/'],
 ['/117538224/'],
 ['/115520175/'],
 ['/117537442/'],
 ['/117535559/'],
 ['/117534092/'],
 ['/117533318/'],
 ['/108572408/'],
 ['/119886545/'],
 ['/119930043/'],
 ['/119936024/'],
 ['/119877819/'],
 ['/119538126/'],
 ['/119538130/'],
 ['/119828763/'],
 ['/119838570/'],
 ['/119838581/'],
 ['/119842246/'],
 ['/119789623/'],
 ['/119759641/'],
 ['/119786235/'],
 ['/119798071/'],
 ['/119756312/'],
 ['/119690045/'],
 ['/119651182/'],
 ['/119624083/'],
 ['/119560127/'],
 ['/119427519/'],
 ['/119444578/'],
 ['/119412149/'],
 ['/119342835/'],
 ['/119475045/'],
 ['/119419907/'],
 ['/119422390/'],
 ['/119425550/'],
 ['/119309049/'],
 ['/119324857/'],
 ['/119190462/'],
 ['/119232476/'],
 ['/119201347/'],
 ['/119213018/'],
 ['/119159620/'],
 ['/119101475/'],
 ['/119120704/'],
 ['/119126019/'],
 ['/119067975/'],
 ['/118833865/'],
 ['/118930903/'],
 ['/118898826/'],
 ['/118870997/'],
 ['/118850018/'],
 ['/118748607/'],
 ['/118725318/'],
 ['/118604342/'],
 ['/118451764/'],
 ['/118458299/'],
 ['/118377498/'],
 ['/118346101/'],
 ['/118284686/'],
 ['/118728928/'],
 ['/118196437/'],
 ['/118155744/'],
 ['/118090517/'],
 ['/118090520/'],
 ['/118072034/'],
 ['/117801849/'],
 ['/117621019/'],
 ['/117621439/'],
 ['/116216391/'],
 ['/116117107/'],
 ['/115676725/'],
 ['/115676810/'],
 ['/115321636/'],
 ['/115186785/'],
 ['/115049465/'],
 ['/117536867/'],
 ['/117657024/'],
 ['/117534957/'],
 ['/117532814/'],
 ['/119798079/'],
 ['/119859057/'],
 ['/119662954/'],
 ['/119612436/'],
 ['/119559479/'],
 ['/119524140/'],
 ['/119546738/'],
 ['/119477740/'],
 ['/119341244/'],
 ['/119201351/'],
 ['/119204635/'],
 ['/119067996/'],
 ['/119120693/'],
 ['/119120714/'],
 ['/119071876/'],
 ['/119072543/'],
 ['/118994458/'],
 ['/118928359/'],
 ['/118783108/'],
 ['/118731308/'],
 ['/119759643/'],
 ['/119778980/'],
 ['/119724258/'],
 ['/119583073/'],
 ['/119634576/'],
 ['/119612347/'],
 ['/119463866/'],
 ['/119328527/'],
 ['/119199678/'],
 ['/119232475/'],
 ['/119148662/'],
 ['/119109777/'],
 ['/119082577/'],
 ['/118975159/'],
 ['/118934647/'],
 ['/118890791/'],
 ['/118851163/'],
 ['/118755730/'],
 ['/118612879/'],
 ['/118051393/'],
 ['/119913668/'],
 ['/119923773/'],
 ['/119788449/'],
 ['/119612312/'],
 ['/119742788/'],
 ['/119716956/'],
 ['/119663962/'],
 ['/119624109/'],
 ['/119633818/'],
 ['/119514328/'],
 ['/119527426/'],
 ['/119476732/'],
 ['/119270886/'],
 ['/119507131/'],
 ['/119044464/'],
 ['/119142882/'],
 ['/119169252/'],
 ['/119227144/'],
 ['/118943502/'],
 ['/119105709/'],
 ['/119011564/'],
 ['/118924082/'],
 ['/118780058/'],
 ['/118746389/'],
 ['/118636547/'],
 ['/118581555/'],
 ['/118531835/'],
 ['/118517713/'],
 ['/118441951/'],
 ['/118451774/'],
 ['/118454727/'],
 ['/118142818/'],
 ['/117929336/'],
 ['/117909393/'],
 ['/117863861/'],
 ['/117697649/'],
 ['/117716099/'],
 ['/116216107/'],
 ['/116196246/'],
 ['/116196215/'],
 ['/116115847/'],
 ['/115932647/'],
 ['/115519974/'],
 ['/115389906/'],
 ['/115186776/'],
 ['/115253530/'],
 ['/114100622/'],
 ['/117536992/'],
 ['/117535485/'],
 ['/119738386/'],
 ['/119778951/'],
 ['/119633821/'],
 ['/119627103/'],
 ['/119638078/'],
 ['/119629731/'],
 ['/119467406/'],
 ['/119467407/'],
 ['/119472007/'],
 ['/119439339/'],
 ['/119447028/'],
 ['/119417013/'],
 ['/119232462/'],
 ['/119213020/'],
 ['/119176099/'],
 ['/119103923/'],
 ['/119107593/'],
 ['/119123253/'],
 ['/119086644/'],
 ['/119011531/'],
 ['/118954545/'],
 ['/118917047/'],
 ['/118854259/'],
 ['/118721868/'],
 ['/118722270/'],
 ['/119439348/'],
 ['/118640782/'],
 ['/118431265/'],
 ['/118020590/'],
 ['/118121527/'],
 ['/117596245/'],
 ['/116195544/'],
 ['/115994984/'],
 ['/115994742/'],
 ['/114157812/'],
 ['/113023829/'],
 ['/119954422/'],
 ['/119954433/'],
 ['/119794427/'],
 ['/119947999/'],
 ['/119721617/'],
 ['/119695480/'],
 ['/119659202/'],
 ['/119390698/'],
 ['/119257127/'],
 ['/119254289/'],
 ['/118857854/'],
 ['/119115126/'],
 ['/119127592/'],
 ['/118700460/'],
 ['/118943493/'],
 ['/118907056/'],
 ['/118770422/'],
 ['/118801198/'],
 ['/118680824/'],
 ['/118646721/'],
 ['/118463423/'],
 ['/118527854/'],
 ['/118284621/'],
 ['/118500506/'],
 ['/118520401/'],
 ['/118374971/'],
 ['/118289788/'],
 ['/118229299/'],
 ['/118205775/'],
 ['/118154098/'],
 ['/117998130/'],
 ['/116194942/'],
 ['/115738670/'],
 ['/115676142/'],
 ['/117541301/'],
 ['/115586941/'],
 ['/115321683/'],
 ['/117540722/'],
 ['/117988836/'],
 ['/115049623/'],
 ['/114983144/'],
 ['/114100589/'],
 ['/113183439/'],
 ['/117534817/'],
 ['/111319866/'],
 ['/117533861/'],
 ['/117533337/'],
 ['/117533189/'],
 ['/105521147/'],
 ['/117532717/'],
 ['/119805772/'],
 ['/119760692/'],
 ['/119355698/'],
 ['/119321632/'],
 ['/119254316/'],
 ['/119220306/'],
 ['/119172023/'],
 ['/119187811/'],
 ['/118954540/'],
 ['/118693721/'],
 ['/118785980/'],
 ['/118612865/'],
 ['/118497287/'],
 ['/117890563/'],
 ['/117845679/'],
 ['/116216499/'],
 ['/115115855/'],
 ['/117538119/'],
 ['/117536679/'],
 ['/111864885/'],
 ['/119805772/'],
 ['/119760692/'],
 ['/119355698/'],
 ['/119321632/'],
 ['/119254316/'],
 ['/119220306/'],
 ['/119172023/'],
 ['/119187811/'],
 ['/118954540/'],
 ['/118693721/'],
 ['/118785980/'],
 ['/118612865/'],
 ['/118497287/'],
 ['/117890563/'],
 ['/117845679/'],
 ['/116216499/'],
 ['/115115855/'],
 ['/117538119/'],
 ['/117536679/'],
 ['/111864885/'],
 ['/119855743/'],
 ['/119963169/'],
 ['/119938364/'],
 ['/119762179/'],
 ['/119697041/'],
 ['/119828772/'],
 ['/119771126/'],
 ['/119612488/'],
 ['/119615212/'],
 ['/119618265/'],
 ['/119529080/'],
 ['/119516008/'],
 ['/119385340/'],
 ['/119156796/'],
 ['/119235730/'],
 ['/119168442/'],
 ['/119112672/'],
 ['/119099209/'],
 ['/119522442/'],
 ['/118709785/'],
 ['/118811901/'],
 ['/118774758/'],
 ['/118646693/'],
 ['/118531831/'],
 ['/118545251/'],
 ['/118485482/'],
 ['/118513352/'],
 ['/118448307/'],
 ['/118456346/'],
 ['/118284725/'],
 ['/118172228/'],
 ['/118091048/'],
 ['/118046034/'],
 ['/115994697/'],
 ['/115519758/'],
 ['/115253206/'],
 ['/117539484/'],
 ['/113890354/'],
 ['/117537298/'],
 ['/117533638/'],
 ['/117533547/'],
 ['/119877864/'],
 ['/119898441/'],
 ['/119948009/'],
 ['/119963159/'],
 ['/119910788/'],
 ['/119913667/'],
 ['/119936027/'],
 ['/119753671/'],
 ['/119898435/'],
 ['/119877839/'],
 ['/119805776/'],
 ['/119760688/'],
 ['/119742799/'],
 ['/119751804/'],
 ['/119729200/'],
 ['/119644317/'],
 ['/119612480/'],
 ['/119615214/'],
 ['/119618259/'],
 ['/119621366/'],
 ['/119334804/'],
 ['/119586256/'],
 ['/119595893/'],
 ['/119612419/'],
 ['/119492406/'],
 ['/119567624/'],
 ['/119534982/'],
 ['/119488652/'],
 ['/119492391/'],
 ['/119503853/'],
 ['/119476734/'],
 ['/119409993/'],
 ['/119412144/'],
 ['/119375070/'],
 ['/119317294/'],
 ['/119302785/'],
 ['/119159619/'],
 ['/119240692/'],
 ['/119254308/'],
 ['/119265295/'],
 ['/119220304/'],
 ['/119211831/'],
 ['/119162883/'],
 ['/119024778/'],
 ['/119133543/'],
 ['/119115127/'],
 ['/119126014/'],
 ['/119095165/'],
 ['/119097423/'],
 ['/119060929/'],
 ['/119060950/'],
 ['/119064522/'],
 ['/119064543/'],
 ['/119067999/'],
 ['/119044468/'],
 ['/119023669/'],
 ['/118971144/'],
 ['/118984432/'],
 ['/118934649/'],
 ['/118943538/'],
 ['/118948328/'],
 ['/118951910/'],
 ['/118920811/'],
 ['/118926741/'],
 ['/118890777/'],
 ['/118871057/'],
 ['/118874229/'],
 ['/118893331/'],
 ['/118893332/'],
 ['/118725315/'],
 ['/118744788/'],
 ['/118833897/'],
 ['/118643821/'],
 ['/118764387/'],
 ['/118770412/'],
 ['/118746378/'],
 ['/118746396/'],
 ['/118755728/'],
 ['/118568430/'],
 ['/118577129/'],
 ['/118591944/'],
 ['/118571568/'],
 ['/118538521/'],
 ['/118354762/'],
 ['/118377481/'],
 ['/118427224/'],
 ['/118377461/'],
 ['/118294185/'],
 ['/118242008/'],
 ['/118044019/'],
 ['/118046024/'],
 ['/118023625/'],
 ['/118035867/'],
 ['/118005552/'],
 ['/118018228/'],
 ['/117948885/'],
 ['/117886457/'],
 ['/117817558/'],
 ['/117698736/'],
 ['/116116578/'],
 ['/119078945/'],
 ['/115587058/'],
 ['/115519508/'],
 ['/115389899/'],
 ['/117540418/'],
 ['/117539800/'],
 ['/117538824/'],
 ['/114029051/'],
 ['/113968217/'],
 ['/117536576/'],
 ['/117535924/'],
 ['/117534797/'],
 ['/117685304/'],
 ['/117532454/'],
 ['/119883151/'],
 ['/119823438/'],
 ['/119751827/'],
 ['/119690023/'],
 ['/119690058/'],
 ['/119254297/'],
 ['/119109775/'],
 ['/118476832/'],
 ['/118395637/'],
 ['/118215638/'],
 ['/117893856/'],
 ['/117788365/'],
 ['/116115910/'],
 ['/117534724/'],
 ['/119825932/'],
 ['/119357982/'],
 ['/119571123/'],
 ['/119571130/'],
 ['/119573358/'],
 ['/119507102/'],
 ['/119437303/'],
 ['/119441602/'],
 ['/119447018/'],
 ['/119390688/'],
 ['/119355695/'],
 ['/119355696/'],
 ['/119232464/'],
 ['/119188718/'],
 ['/118926726/'],
 ['/118874218/'],
 ['/118880286/'],
 ['/118822244/'],
 ['/118666415/'],
 ['/118500491/'],
 ['/118451749/'],
 ['/118309174/'],
 ['/118319574/'],
 ['/117890552/'],
 ['/117845710/'],
 ['/117826018/'],
 ['/117691699/'],
 ['/117687849/'],
 ['/117628357/'],
 ['/116116681/'],
 ['/116116731/'],
 ['/116116732/'],
 ['/116116615/'],
 ['/115994237/'],
 ['/115933528/'],
 ['/115869736/'],
 ['/115676949/'],
 ['/115676068/'],
 ['/115520459/'],
 ['/115460835/'],
 ['/115460639/'],
 ['/115321293/'],
 ['/115253773/'],
 ['/114285528/'],
 ['/115739663/'],
 ['/114028917/'],
 ['/117538112/'],
 ['/113433040/'],
 ['/113024125/'],
 ['/117534377/'],
 ['/119848121/'],
 ['/119762186/'],
 ['/119515125/'],
 ['/119775296/'],
 ['/119712285/'],
 ['/119593456/'],
 ['/119564442/'],
 ['/119262242/'],
 ['/119360848/'],
 ['/119300127/'],
 ['/119284134/'],
 ['/119254298/'],
 ['/119009132/'],
 ['/118844292/'],
 ['/118804462/'],
 ['/118693728/'],
 ['/118545259/'],
 ['/118482347/'],
 ['/118337299/'],
 ['/118422051/'],
 ['/118284657/'],
 ['/118263696/'],
 ['/118128029/'],
 ['/117667117/'],
 ['/116196172/'],
 ['/115994738/'],
 ['/115812613/'],
 ['/115519905/'],
 ['/115186595/'],
 ['/117539491/'],
 ['/113432754/'],
 ['/112720734/'],
 ['/112502778/'],
 ['/117534801/'],
 ['/117534638/'],
 ['/119883141/'],
 ['/119648222/'],
 ['/119612497/'],
 ['/119204644/'],
 ['/119019721/'],
 ['/118757837/'],
 ['/118669819/'],
 ['/118513340/'],
 ['/118379028/'],
 ['/118338107/'],
 ['/117540006/'],
 ['/114157629/'],
 ['/117537082/'],
 ['/119963176/'],
 ['/119548670/'],
 ['/119665044/'],
 ['/119577214/'],
 ['/119497439/'],
 ['/119270885/'],
 ['/118700467/'],
 ['/118728930/'],
 ['/118334437/'],
 ['/118329682/'],
 ['/118048371/'],
 ['/119644312/'],
 ['/119091375/'],
 ['/118740090/'],
 ['/118344977/'],
 ['/118046014/'],
 ['/117878696/'],
 ['/117878698/'],
 ['/117791094/'],
 ['/116058167/'],
 ['/115932754/'],
 ['/115519754/'],
 ['/112648213/'],
 ['/117533843/'],
 ['/119805769/'],
 ['/119769638/'],
 ['/119492387/'],
 ['/119497430/'],
 ['/119419892/'],
 ['/119383210/'],
 ['/119319755/'],
 ['/119295520/'],
 ['/119118253/'],
 ['/119091385/'],
 ['/119019719/'],
 ['/118764384/'],
 ['/118752667/'],
 ['/118736470/'],
 ['/118613960/'],
 ['/118400100/'],
 ['/118349936/'],
 ['/118294203/'],
 ['/118224428/'],
 ['/118227350/'],
 ['/117988843/'],
 ['/117803020/'],
 ['/116216051/'],
 ['/117541946/'],
 ['/115676706/'],
 ['/115676156/'],
 ['/115252831/'],
 ['/118058267/'],
 ['/112859534/'],
 ['/117532942/'],
 ['/104342173/'],
 ['/103978309/'],
 ['/119957776/'],
 ['/119818954/'],
 ['/119573369/'],
 ['/119674705/'],
 ['/119413951/'],
 ['/119277289/'],
 ['/119014546/'],
 ['/119067987/'],
 ['/118807387/'],
 ['/118653897/'],
 ['/118590637/'],
 ['/118482344/'],
 ['/118354775/'],
 ['/118289778/'],
 ['/118294219/'],
 ['/117643368/'],
 ['/115869632/'],
 ['/115870441/'],
 ['/115870185/'],
 ['/115676595/'],
 ['/115587556/'],
 ['/113839476/'],
 ['/113624640/'],
 ['/109557355/'],
 ['/119930033/'],
 ['/119724263/'],
 ['/119708145/'],
 ['/119708146/'],
 ['/119589277/'],
 ['/119503868/'],
 ['/119339169/'],
 ['/119344408/'],
 ['/119257112/'],
 ['/119152603/'],
 ['/119164286/'],
 ['/119086640/'],
 ['/119095155/'],
 ['/119011545/'],
 ['/118871040/'],
 ['/118888177/'],
 ['/118890775/'],
 ['/118818480/'],
 ['/118822229/'],
 ['/118774756/'],
 ['/118409191/'],
 ['/118427193/'],
 ['/118333688/'],
 ['/118173851/'],
 ['/118089138/'],
 ['/118005555/'],
 ['/118027641/'],
 ['/117929338/'],
 ['/117557071/'],
 ['/116194470/'],
 ['/116116036/'],
 ['/115869808/'],
 ['/115389486/'],
 ['/117537333/'],
 ['/117537120/'],
 ['/117536698/'],
 ['/113136134/'],
 ['/117534805/'],
 ['/117532897/'],
 ['/105524874/'],
 ['/119166392/'],
 ['/119095163/'],
 ['/118669847/'],
 ['/118590630/'],
 ['/119935328/'],
 ['/119792099/'],
 ['/119515129/'],
 ['/118958919/'],
 ['/119038697/'],
 ['/119045716/'],
 ['/118943533/'],
 ['/118738557/'],
 ['/118697846/'],
 ['/116195702/'],
 ['/116116452/'],
 ['/114930351/']]

###
### We will now iterate through each webpage, and extract the data we want

In [11]:
final = []
i=0
for link in links:
    

    try:
        data = {}
    
        temp = []
        
        url = f'https://www.weichert.com{link[0]}'
        res = requests.get(url)
        soup = BeautifulSoup(res.text, 'html.parser')
    
        # Scraping Market Price and Sq Ft
        mainDiv = soup.find('div', class_='col-sm-9 col-md-9 propertyAddressSection')
    
        for element in mainDiv:
            temp.append(element.text.strip())
            
        temp.pop(0)
        price = float(temp[1].replace('$', '').replace(',','').strip())
        sqft = int(temp[-1].split()[-1].replace(',',''))
        data = {'Price' : price, 'Sq Ft' : sqft}
    
        # Scraping other information (varies)
        mainDiv = soup.find('div', class_='listing-features shift-div-left')
        for primary in mainDiv:
            for secondary in primary:
                divs = secondary.find_all('div', class_='col-xs-6')
                if divs[0].text != 'Price':
                    data[divs[0].text] = divs[-1].text

        # Average List Price and Median Income of town/city (Cleaned on the spot)
        mainDiv = soup.find('div', class_='property-type-stat')
        listPrice = mainDiv.find('span', class_='market-list-value').text.replace(',','').replace('$','')
        mainDiv = soup.find('div', id='medianIncome')
        medianIncome = mainDiv.find('span', class_='population-data-display').text.replace(',','').replace('$','').strip()
        data['Town/City Median Income'] = medianIncome
        final.append(data)
        i+=1
        print(f'Iteration - {i}')

    
    except:
        print('Error. Link will be ignored')

Iteration - 1
Iteration - 2
Iteration - 3
Error. Link will be ignored
Iteration - 4
Iteration - 5
Iteration - 6
Iteration - 7
Iteration - 8
Iteration - 9
Iteration - 10
Iteration - 11
Iteration - 12
Iteration - 13
Iteration - 14
Iteration - 15
Iteration - 16
Iteration - 17
Iteration - 18
Iteration - 19
Iteration - 20
Iteration - 21
Iteration - 22
Iteration - 23
Iteration - 24
Iteration - 25
Iteration - 26
Iteration - 27
Iteration - 28
Iteration - 29
Iteration - 30
Iteration - 31
Iteration - 32
Iteration - 33
Iteration - 34
Iteration - 35
Iteration - 36
Iteration - 37
Iteration - 38
Iteration - 39
Iteration - 40
Iteration - 41
Iteration - 42
Error. Link will be ignored
Iteration - 43
Iteration - 44
Iteration - 45
Iteration - 46
Iteration - 47
Iteration - 48
Iteration - 49
Iteration - 50
Iteration - 51
Iteration - 52
Iteration - 53
Iteration - 54
Iteration - 55
Iteration - 56
Iteration - 57
Iteration - 58
Iteration - 59
Iteration - 60
Iteration - 61
Iteration - 62
Iteration - 63
Iteration - 64
Iteration - 65
Iteration - 66
Iteration - 67
Iteration - 68
Iteration - 69
Iteration - 70
Iteration - 71
Iteration - 72
Iteration - 73
Iteration - 74
Iteration - 75
Iteration - 76
Error. Link will be ignored
Iteration - 77
Iteration - 78
Iteration - 79
Iteration - 80
Iteration - 81
Iteration - 82
Iteration - 83
Iteration - 84
Iteration - 85
Iteration - 86
Iteration - 87
Iteration - 88
Error. Link will be ignored
Iteration - 89
Iteration - 90
Iteration - 91
Iteration - 92
Iteration - 93
Iteration - 94
Iteration - 95
Iteration - 96
Iteration - 97
Iteration - 98
Iteration - 99
Iteration - 100
Iteration - 101
Iteration - 102
Iteration - 103
Iteration - 104
Iteration - 105
Iteration - 106
Iteration - 107
Iteration - 108
Iteration - 109
Iteration - 110
Iteration - 111
Iteration - 112
Iteration - 113
Iteration - 114
Iteration - 115
Iteration - 116
Iteration - 117
Iteration - 118
Iteration - 119
Iteration - 120
Iteration - 121
Iteration - 122
Iteration - 123
Iteration - 124
Iteration - 125
Iteration - 126
Iteration - 127
Iteration - 128
Iteration - 129
Iteration - 130
Iteration - 131
Iteration - 132
Iteration - 133
Iteration - 134
Iteration - 135
Iteration - 136
Iteration - 137
Iteration - 138
Iteration - 139
Iteration - 140
Iteration - 141
Iteration - 142
Iteration - 143
Iteration - 144
Iteration - 145
Iteration - 146
Iteration - 147
Iteration - 148
Iteration - 149
Iteration - 150
Iteration - 151
Iteration - 152
Error. Link will be ignored
Iteration - 153
Iteration - 154
Iteration - 155
Iteration - 156
Error. Link will be ignored
Iteration - 157
Iteration - 158
Iteration - 159
Error. Link will be ignored
Iteration - 160
Iteration - 161
Iteration - 162
Error. Link will be ignored
Iteration - 163
Iteration - 164
Iteration - 165
Iteration - 166
Iteration - 167
Iteration - 168
Iteration - 169
Iteration - 170
Iteration - 171
Iteration - 172
Iteration - 173
Iteration - 174
Iteration - 175
Iteration - 176
Iteration - 177
Iteration - 178
Iteration - 179
Iteration - 180
Iteration - 181
Iteration - 182
Iteration - 183
Iteration - 184
Iteration - 185
Iteration - 186
Iteration - 187
Iteration - 188
Iteration - 189
Iteration - 190
Iteration - 191
Iteration - 192
Iteration - 193
Iteration - 194
Iteration - 195
Iteration - 196
Iteration - 197
Iteration - 198
Iteration - 199
Iteration - 200
Iteration - 201
Iteration - 202
Iteration - 203
Iteration - 204
Iteration - 205
Iteration - 206
Iteration - 207
Iteration - 208
Error. Link will be ignored
Iteration - 209
Iteration - 210
Iteration - 211
Iteration - 212
Iteration - 213
Iteration - 214
Iteration - 215
Iteration - 216
Iteration - 217
Iteration - 218
Iteration - 219
Iteration - 220
Iteration - 221
Iteration - 222
Error. Link will be ignored
Iteration - 223
Iteration - 224
Iteration - 225
Iteration - 226
Iteration - 227
Iteration - 228
Iteration - 229
Iteration - 230
Iteration - 231
Iteration - 232
Iteration - 233
Iteration - 234
Iteration - 235
Iteration - 236
Iteration - 237
Iteration - 238
Iteration - 239
Iteration - 240
Iteration - 241
Iteration - 242
Iteration - 243
Iteration - 244
Iteration - 245
Iteration - 246
Iteration - 247
Iteration - 248
Iteration - 249
Error. Link will be ignored
Iteration - 250
Iteration - 251
Iteration - 252
Iteration - 253
Iteration - 254
Iteration - 255
Iteration - 256
Iteration - 257
Iteration - 258
Iteration - 259
Iteration - 260
Iteration - 261
Iteration - 262
Iteration - 263
Iteration - 264
Iteration - 265
Iteration - 266
Iteration - 267
Iteration - 268
Iteration - 269
Iteration - 270
Iteration - 271
Iteration - 272
Iteration - 273
Iteration - 274
Iteration - 275
Iteration - 276
Iteration - 277
Iteration - 278
Iteration - 279
Iteration - 280
Iteration - 281
Iteration - 282
Iteration - 283
Iteration - 284
Iteration - 285
Iteration - 286
Iteration - 287
Iteration - 288
Iteration - 289
Iteration - 290
Iteration - 291
Iteration - 292
Iteration - 293
Iteration - 294
Iteration - 295
Iteration - 296
Iteration - 297
Iteration - 298
Error. Link will be ignored
Iteration - 299
Iteration - 300
Iteration - 301
Iteration - 302
Iteration - 303
Iteration - 304
Iteration - 305
Iteration - 306
Iteration - 307
Iteration - 308
Iteration - 309
Iteration - 310
Iteration - 311
Iteration - 312
Iteration - 313
Iteration - 314
Iteration - 315
Iteration - 316
Iteration - 317
Error. Link will be ignored
Error. Link will be ignored
Iteration - 318
Iteration - 319
Iteration - 320
Iteration - 321
Iteration - 322
Iteration - 323
Iteration - 324
Iteration - 325
Iteration - 326
Iteration - 327
Iteration - 328
Iteration - 329
Iteration - 330
Iteration - 331
Iteration - 332
Iteration - 333
Iteration - 334
Iteration - 335
Iteration - 336
Iteration - 337
Iteration - 338
Error. Link will be ignored
Iteration - 339
Iteration - 340
Iteration - 341
Iteration - 342
Iteration - 343
Iteration - 344
Iteration - 345
Iteration - 346
Iteration - 347
Iteration - 348
Iteration - 349
Iteration - 350
Iteration - 351
Iteration - 352
Iteration - 353
Iteration - 354
Iteration - 355
Iteration - 356
Iteration - 357
Iteration - 358
Iteration - 359
Iteration - 360
Iteration - 361
Iteration - 362
Iteration - 363
Iteration - 364
Iteration - 365
Iteration - 366
Iteration - 367
Iteration - 368
Iteration - 369
Iteration - 370
Iteration - 371
Iteration - 372
Iteration - 373
Iteration - 374
Iteration - 375
Iteration - 376
Iteration - 377
Iteration - 378
Iteration - 379
Iteration - 380
Iteration - 381
Iteration - 382
Iteration - 383
Iteration - 384
Iteration - 385
Iteration - 386
Iteration - 387
Iteration - 388
Iteration - 389
Iteration - 390
Iteration - 391
Iteration - 392
Iteration - 393
Iteration - 394
Iteration - 395
Iteration - 396
Iteration - 397
Iteration - 398
Iteration - 399
Iteration - 400
Iteration - 401
Iteration - 402
Iteration - 403
Iteration - 404
Iteration - 405
Iteration - 406
Iteration - 407
Error. Link will be ignored
Iteration - 408
Error. Link will be ignored
Iteration - 409
Iteration - 410
Iteration - 411
Iteration - 412
Iteration - 413
Iteration - 414
Iteration - 415
Iteration - 416
Error. Link will be ignored
Error. Link will be ignored
Iteration - 417
Iteration - 418
Iteration - 419
Iteration - 420
Iteration - 421
Iteration - 422
Iteration - 423
Iteration - 424
Iteration - 425
Iteration - 426
Iteration - 427
Iteration - 428
Iteration - 429
Iteration - 430
Iteration - 431
Iteration - 432
Error. Link will be ignored
Iteration - 433
Iteration - 434
Iteration - 435
Iteration - 436
Iteration - 437
Iteration - 438
Iteration - 439
Iteration - 440
Iteration - 441
Iteration - 442
Iteration - 443
Iteration - 444
Iteration - 445
Iteration - 446
Iteration - 447
Iteration - 448
Iteration - 449
Iteration - 450
Iteration - 451
Iteration - 452
Iteration - 453
Iteration - 454
Iteration - 455
Iteration - 456
Iteration - 457
Iteration - 458
Iteration - 459
Iteration - 460
Iteration - 461
Iteration - 462
Iteration - 463
Iteration - 464
Iteration - 465
Iteration - 466
Iteration - 467
Iteration - 468
Iteration - 469
Iteration - 470
Iteration - 471
Iteration - 472
Iteration - 473
Iteration - 474
Iteration - 475
Error. Link will be ignored
Iteration - 476
Iteration - 477
Iteration - 478
Iteration - 479
Iteration - 480
Iteration - 481
Error. Link will be ignored
Iteration - 482
Iteration - 483
Iteration - 484
Iteration - 485
Iteration - 486
Iteration - 487
Iteration - 488
Iteration - 489
Iteration - 490
Iteration - 491
Iteration - 492
Iteration - 493
Iteration - 494
Iteration - 495
Iteration - 496
Iteration - 497
Iteration - 498
Iteration - 499
Iteration - 500
Iteration - 501
Iteration - 502
Iteration - 503
Iteration - 504
Iteration - 505
Iteration - 506
Iteration - 507
Iteration - 508
Iteration - 509
Iteration - 510
Iteration - 511
Iteration - 512
Iteration - 513
Iteration - 514
Iteration - 515
Iteration - 516
Iteration - 517
Error. Link will be ignored
Iteration - 518
Error. Link will be ignored
Iteration - 519
Iteration - 520
Iteration - 521
Iteration - 522
Iteration - 523
Iteration - 524
Iteration - 525
Iteration - 526
Iteration - 527
Iteration - 528
Iteration - 529
Iteration - 530
Iteration - 531
Error. Link will be ignored
Iteration - 532
Iteration - 533
Iteration - 534
Iteration - 535
Iteration - 536
Iteration - 537
Iteration - 538
Iteration - 539
Iteration - 540
Iteration - 541
Iteration - 542
Iteration - 543
Iteration - 544
Iteration - 545
Iteration - 546
Iteration - 547
Iteration - 548
Iteration - 549
Iteration - 550
Iteration - 551
Iteration - 552
Iteration - 553
Error. Link will be ignored
Iteration - 554
Iteration - 555
Iteration - 556
Error. Link will be ignored
Iteration - 557
Iteration - 558
Iteration - 559
Iteration - 560
Iteration - 561
Iteration - 562
Iteration - 563
Iteration - 564
Iteration - 565
Error. Link will be ignored
Iteration - 566
Error. Link will be ignored
Error. Link will be ignored
Iteration - 567
Iteration - 568
Iteration - 569
Iteration - 570
Iteration - 571
Iteration - 572
Iteration - 573
Iteration - 574
Iteration - 575
Error. Link will be ignored
Error. Link will be ignored
Iteration - 576
Error. Link will be ignored
Iteration - 577
Iteration - 578
Error. Link will be ignored
Iteration - 579
Iteration - 580
Error. Link will be ignored
Error. Link will be ignored
Iteration - 581
Iteration - 582
Iteration - 583
Iteration - 584
Iteration - 585
Error. Link will be ignored
Iteration - 586
Error. Link will be ignored
Iteration - 587
Iteration - 588
Error. Link will be ignored
Iteration - 589
Iteration - 590
Iteration - 591
Iteration - 592
Iteration - 593
Iteration - 594
Iteration - 595
Iteration - 596
Iteration - 597
Iteration - 598
Iteration - 599
Iteration - 600
Iteration - 601
Iteration - 602
Iteration - 603
Iteration - 604
Error. Link will be ignored
Iteration - 605
Iteration - 606
Iteration - 607
Iteration - 608
Iteration - 609
Iteration - 610
Iteration - 611
Iteration - 612
Iteration - 613
Iteration - 614
Iteration - 615
Iteration - 616
Iteration - 617
Iteration - 618
Iteration - 619
Iteration - 620
Iteration - 621
Iteration - 622
Iteration - 623
Iteration - 624
Iteration - 625
Iteration - 626
Iteration - 627
Iteration - 628
Iteration - 629
Iteration - 630
Iteration - 631
Iteration - 632
Iteration - 633
Iteration - 634
Iteration - 635
Error. Link will be ignored
Iteration - 636
Iteration - 637
Iteration - 638
Iteration - 639
Iteration - 640
Iteration - 641
Iteration - 642
Iteration - 643
Iteration - 644
Iteration - 645
Iteration - 646
Iteration - 647
Iteration - 648
Error. Link will be ignored
Iteration - 649
Iteration - 650
Iteration - 651
Iteration - 652
Iteration - 653
Iteration - 654
Iteration - 655
Iteration - 656
Iteration - 657
Iteration - 658
Iteration - 659
Iteration - 660
Iteration - 661
Iteration - 662
Iteration - 663
Iteration - 664
Iteration - 665
Iteration - 666
Iteration - 667
Iteration - 668
Iteration - 669
Iteration - 670
Iteration - 671
Iteration - 672
Iteration - 673
Error. Link will be ignored
Iteration - 674
Iteration - 675
Iteration - 676
Iteration - 677
Iteration - 678
Iteration - 679
Iteration - 680
Error. Link will be ignored
Iteration - 681
Iteration - 682
Iteration - 683
Iteration - 684
Iteration - 685
Iteration - 686
Iteration - 687
Iteration - 688
Iteration - 689
Iteration - 690
Iteration - 691
Iteration - 692
Iteration - 693
Iteration - 694
Iteration - 695
Iteration - 696
Iteration - 697
Iteration - 698
Iteration - 699
Iteration - 700
Iteration - 701
Iteration - 702
Iteration - 703
Iteration - 704
Iteration - 705
Iteration - 706
Iteration - 707
Iteration - 708
Iteration - 709
Iteration - 710
Iteration - 711
Iteration - 712
Iteration - 713
Iteration - 714
Iteration - 715
Iteration - 716
Iteration - 717
Iteration - 718
Iteration - 719
Iteration - 720
Error. Link will be ignored
Iteration - 721
Iteration - 722
Error. Link will be ignored
Error. Link will be ignored
Iteration - 723
Iteration - 724
Iteration - 725
Error. Link will be ignored
Iteration - 726
Error. Link will be ignored
Iteration - 727
Iteration - 728
Iteration - 729
Error. Link will be ignored
Iteration - 730
Error. Link will be ignored
Error. Link will be ignored
Iteration - 731
Iteration - 732
Iteration - 733
Error. Link will be ignored
Iteration - 734
Error. Link will be ignored
Iteration - 735
Error. Link will be ignored
Iteration - 736
Iteration - 737
Error. Link will be ignored
Iteration - 738
Iteration - 739
Iteration - 740
Iteration - 741
Iteration - 742
Iteration - 743
Iteration - 744
Error. Link will be ignored
Error. Link will be ignored
Iteration - 745
Iteration - 746
Iteration - 747
Iteration - 748
Error. Link will be ignored
Iteration - 749
Iteration - 750
Error. Link will be ignored
Iteration - 751
Error. Link will be ignored

In [12]:
len(final)

751

In [13]:
final = pd.DataFrame(final)

In [20]:
final.Price

0      1950000.0
1       995000.0
2      1026000.0
3      1325000.0
4      2395000.0
         ...
746    1680000.0
747    1138000.0
748     515000.0
749    1050000.0
750    1249000.0
Name: Price, Length: 751, dtype: float64

#
# Checkpoint for scraped data

In [15]:
final.to_csv('checkpoint.csv', index=False)

In [26]:
final = pd.read_csv('checkpoint.csv')
final

,Price,Sq Ft,Bedrooms,Full Bath,Half Bath,Property Type,Taxes,Style,Lot Size,Year Built,Town/City,County/Region,MLS | Web ID,Town/City Median Income
0,1950000.0,3388,5,4.0,1.0,Single Family,"$ 23,670",Contemporary,0.13,1968.0,Oyster Bay,Nassau,3547293,117085
1,995000.0,6192,4,1.0,2.0,Single Family,"$ 15,009",Victorian,0.14,1903.0,Oyster Bay,Nassau,3543808,117085
2,1026000.0,12001,Studio,NaN,NaN,Commercial,"$ 18,132",NaN,0.28,1900.0,Oyster Bay,Nassau,3543177,117085
3,1325000.0,3582,5,3.0,1.0,Single Family,"$ 17,621",Cape Cod,0.21,1905.0,Oyster Bay,Nassau,3539137,117085
4,2395000.0,87338,5,5.0,1.0,Single Family,"$ 29,241",Colonial,2.01,1984.0,Oyster Bay,Nassau,3538555,117085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,1680000.0,11400,4,4.0,1.0,Single Family,"$ 19,209",Colonial,0.26,1925.0,Great Neck,Nassau,3537216,80809
747,1138000.0,2286,3,3.0,NaN,Single Family,"$ 20,893",Split Level,0.30,1957.0,Great Neck,Nassau,3537341,80809
748,515000.0,1200,2,2.0,NaN,Co-Op,$ 0,High Rise,NaN,1960.0,Great Neck,Nassau,3533891,80809
749,1050000.0,13687,5,2.0,1.0,Single Family,"$ 15,836",Colonial,0.31,1958.0,Great Neck,Nassau,3533458,80809
750,1249000.0,1774,3,2.0,NaN,Single Family,"$ 14,223",NaN,0.44,1920.0,Great Neck,Nassau,3518695,80809

#
# Cleaning/Wrangling

###
### Changing all null values for column: 'Half bath', to 0
### Also removing all rows with a null value. This is done afterwards so we dont drop homes with 0 half-baths

In [27]:
final.loc[final['Half Bath'].isnull(), 'Half Bath']= 0
final = final.dropna()
final = final.reset_index(drop=True)
final.head(3)

,Price,Sq Ft,Bedrooms,Full Bath,Half Bath,Property Type,Taxes,Style,Lot Size,Year Built,Town/City,County/Region,MLS | Web ID,Town/City Median Income
0,1950000.0,3388,5,4.0,1.0,Single Family,"$ 23,670",Contemporary,0.13,1968.0,Oyster Bay,Nassau,3547293,117085
1,995000.0,6192,4,1.0,2.0,Single Family,"$ 15,009",Victorian,0.14,1903.0,Oyster Bay,Nassau,3543808,117085
2,1325000.0,3582,5,3.0,1.0,Single Family,"$ 17,621",Cape Cod,0.21,1905.0,Oyster Bay,Nassau,3539137,117085

###
### Removing all Studios, Condos, TownHouses, and Co-Ops

In [28]:
final = final[final['Bedrooms'] != ' Studio ']
final = final[final['Property Type'] != ' Condo ']
final = final[final['Property Type'] != ' Townhouse ']
final = final[final['Property Type'] != ' Co-Op ']


final = final.reset_index(drop=True)

###
### Dropping unnecessary columns

In [29]:
final.drop(['MLS | Web ID'], axis=1, inplace=True)
final.drop(['County/Region'], axis=1, inplace=True)
final.drop(['Style'], axis=1, inplace=True)
final.drop(['Taxes'], axis=1, inplace=True)
final.head()

,Price,Sq Ft,Bedrooms,Full Bath,Half Bath,Property Type,Lot Size,Year Built,Town/City,Town/City Median Income
0,1950000.0,3388,5,4.0,1.0,Single Family,0.13,1968.0,Oyster Bay,117085
1,995000.0,6192,4,1.0,2.0,Single Family,0.14,1903.0,Oyster Bay,117085
2,1325000.0,3582,5,3.0,1.0,Single Family,0.21,1905.0,Oyster Bay,117085
3,2395000.0,87338,5,5.0,1.0,Single Family,2.01,1984.0,Oyster Bay,117085
4,989000.0,14810,4,3.0,1.0,Multi-Family,0.34,1930.0,Oyster Bay,117085

In [30]:
final['Town/City'].value_counts()

Town/City
Massapequa         86
Port Washington    78
Bethpage           63
Valley Stream      51
Merrick            35
Wantagh            32
New Hyde Park      27
Westbury           26
Island Park        26
Hewlett            23
Albertson          20
Old Bethpage       20
Glen Head          17
Oyster Bay         14
Carle Place        13
Sea Cliff          13
Williston Park     12
East Rockaway      12
East Norwich       11
Massapequa Park    10
East Williston      9
Floral Park         9
Seaford             9
Elmont              6
Great Neck          5
Garden City         5
South Hempstead     4
Rosedale            4
Lynbrook            3
Amityville          3
Franklin Square     3
Woodmere            1
Jamaica             1
Name: count, dtype: int64

###
# FIRST/SECOND BATCH CODE IGNORE
### If we take a look at the value counts of the column: Town/City, there are two distinct values: Garden City South and Stewart Manor
### We will now change these values to Garden City since the zip codes are the same despite the different value

In [92]:
outsider = final['Town/City'].value_counts().index[-1]
index = final[final['Town/City'] == outsider].index[0]
final.loc[index, 'Town/City'] = 'Garden City'

final['Town/City'].value_counts()

Town/City
Massapequa          156
Valley Stream       148
Westbury            129
Levittown           109
Hempstead           108
Freeport            108
Hicksville          101
Elmont               98
Merrick              98
Syosset              91
Plainview            89
New Hyde Park        84
Oceanside            81
Great Neck           80
East Meadow          77
Baldwin              77
Port Washington      73
Wantagh              69
West Hempstead       65
Rockville Centre     65
Manhasset            63
Garden City          59
Farmingdale          55
Seaford              54
Jericho              52
Bellmore             52
Bellerose            47
Lynbrook             45
East Rockaway        42
Franklin Square      41
Floral Park          40
Woodmere             39
Uniondale            37
North Bellmore       35
Old Westbury         35
Roosevelt            35
Mineola              35
East Hills           33
Roslyn Heights       29
Lawrence             27
Roslyn               26
Cedarhurst           24
Malverne             24
Locust Valley        24
Woodbury             23
Inwood               19
Name: count, dtype: int64

In [107]:
outsider = final['Town/City Median Income'].value_counts().index[-1]
index = final[final['Town/City Median Income'] == outsider].index
final.loc[index, 'Town/City Median Income'] =  148988

final['Town/City Median Income'].value_counts()

Town/City Median Income
109697    156
82417     148
94101     129
104835    109
99191     108
71748     108
100344    101
92285      98
132835     98
153880     91
133630     89
99037      84
103596     81
80809      80
96698      77
50750      77
119164     73
118171     69
102689     65
110464     65
168133     63
148988     59
91599      55
116467     54
152678     52
118090     52
80639      47
87014      45
88621      42
98226      41
102922     40
138267     39
73096      37
106190     35
182520     35
74884      35
90940      35
194744     33
123012     29
43244      27
149548     26
102920     24
107442     24
115382     24
161484     23
50497      19
Name: count, dtype: int64

In [31]:
final

,Price,Sq Ft,Bedrooms,Full Bath,Half Bath,Property Type,Lot Size,Year Built,Town/City,Town/City Median Income
0,1950000.0,3388,5,4.0,1.0,Single Family,0.13,1968.0,Oyster Bay,117085
1,995000.0,6192,4,1.0,2.0,Single Family,0.14,1903.0,Oyster Bay,117085
2,1325000.0,3582,5,3.0,1.0,Single Family,0.21,1905.0,Oyster Bay,117085
3,2395000.0,87338,5,5.0,1.0,Single Family,2.01,1984.0,Oyster Bay,117085
4,989000.0,14810,4,3.0,1.0,Multi-Family,0.34,1930.0,Oyster Bay,117085
...,...,...,...,...,...,...,...,...,...,...
646,1088000.0,7622,4,2.0,1.0,Single Family,0.17,1973.0,Great Neck,80809
647,999999.0,7740,3,2.0,0.0,Single Family,0.18,1925.0,Great Neck,80809
648,1680000.0,11400,4,4.0,1.0,Single Family,0.26,1925.0,Great Neck,80809
649,1138000.0,2286,3,3.0,0.0,Single Family,0.30,1957.0,Great Neck,80809
650,1050000.0,13687,5,2.0,1.0,Single Family,0.31,1958.0,Great Neck,80809

##
## We will now update 'Scraped-Cleaned-HomeData.csv')

In [32]:
oldFinal = pd.read_csv('Scraped-Cleaned-HomeData.csv')
oldFinal

,Price,Sq Ft,Bedrooms,Full Bath,Property Type,Lot Size,Year Built,Town/City,Town/City Median Income,Half Bath
0,550000.0,4500,4,2.0,Single Family,0.10,1957.0,Hempstead,99191,0.0
1,549999.0,7020,3,1.0,Single Family,0.16,1940.0,Hempstead,99191,1.0
2,659000.0,5400,6,2.0,Multi-Family,0.12,1962.0,Hempstead,99191,0.0
3,799000.0,6050,3,3.0,Single Family,0.14,1935.0,Hempstead,99191,1.0
4,945000.0,2280,3,2.0,Single Family,0.25,1948.0,Hempstead,99191,1.0
...,...,...,...,...,...,...,...,...,...,...
2896,5830000.0,14835,11,8.0,Single Family,0.96,2016.0,Lawrence,43244,1.0
2897,3100000.0,4480,5,4.0,Single Family,0.37,1959.0,Lawrence,43244,1.0
2898,1275000.0,19079,4,2.0,Single Family,0.44,1951.0,Lawrence,43244,1.0
2899,1850000.0,33706,11,4.0,Multi-Family,0.77,1900.0,Lawrence,43244,0.0
2900,3100000.0,9890,4,2.0,Single Family,0.23,1964.0,Lawrence,43244,2.0

In [33]:
final = pd.concat([final, oldFinal], axis = 0, ignore_index=True)
final

,Price,Sq Ft,Bedrooms,Full Bath,Half Bath,Property Type,Lot Size,Year Built,Town/City,Town/City Median Income
0,1950000.0,3388,5,4.0,1.0,Single Family,0.13,1968.0,Oyster Bay,117085
1,995000.0,6192,4,1.0,2.0,Single Family,0.14,1903.0,Oyster Bay,117085
2,1325000.0,3582,5,3.0,1.0,Single Family,0.21,1905.0,Oyster Bay,117085
3,2395000.0,87338,5,5.0,1.0,Single Family,2.01,1984.0,Oyster Bay,117085
4,989000.0,14810,4,3.0,1.0,Multi-Family,0.34,1930.0,Oyster Bay,117085
...,...,...,...,...,...,...,...,...,...,...
3547,5830000.0,14835,11,8.0,1.0,Single Family,0.96,2016.0,Lawrence,43244
3548,3100000.0,4480,5,4.0,1.0,Single Family,0.37,1959.0,Lawrence,43244
3549,1275000.0,19079,4,2.0,1.0,Single Family,0.44,1951.0,Lawrence,43244
3550,1850000.0,33706,11,4.0,0.0,Multi-Family,0.77,1900.0,Lawrence,43244
3551,3100000.0,9890,4,2.0,2.0,Single Family,0.23,1964.0,Lawrence,43244

In [34]:
final.to_csv('Scraped-Cleaned-HomeData.csv', index=False)